
export const EXECUTIVE_SUMMARY_TOC = [
    { id: "intro", title: "Introduction" },
    { id: "gvi", title: "General Visual Inspection (GVI)" },
    { id: "cp", title: "Cathodic Potential (CP) Survey" },
    { id: "fmd", title: "Flooded Member Detection" },
    { id: "caisson_top", title: "Caisson Survey Topside" },
    { id: "caisson_sub", title: "Caisson Survey Subsea" },
    { id: "boatlanding_top", title: "Boat Landing Inspection Topside" },
    { id: "boatlanding_sub", title: "Boat Landing Inspection Subsea" },
    { id: "riserguard_top", title: "Riser Guard Inspection Topside" },
    { id: "riserguard_sub", title: "Riser Guard Inspection Subsea" },
    { id: "conductor_top", title: "Conductors Inspection Topside" },
    { id: "conductor_sub", title: "Conductors Inspection Subsea" },
    { id: "riser", title: "Riser Inspection" },
    { id: "splashzone", title: "Splashzone Coating Inspection" },
    { id: "anode_gen", title: "General Anode Inspection" },
    { id: "anode_sel", title: "Selected Anode Inspection" },
    { id: "mgi", title: "Marine Growth Inspection" },
    { id: "scour", title: "Base Level / Scour Survey" },
    { id: "seabed", title: "Seabed Survey" },
    { id: "anode_maint", title: "Anode Maintenance Work" },
    { id: "node_cvi", title: "Selected Node - Close Visual Inspection" },
    { id: "node_mpi", title: "Selected Node - Magnetic Particle Inspection" },
    { id: "boatbumper_top", title: "Boat Bumper Inspection Topside" },
    { id: "boatbumper_sub", title: "Boat Bumper Inspection Subsea" },
    { id: "conductorguard_sub", title: "Conductor Guard Inspection Subsea" },
    { id: "caissonguard_sub", title: "Caisson Guard Inspection Subsea" },
    { id: "conductorguard_top", title: "Conductor Guard Inspection Topside" },
    { id: "caissonguard_top", title: "Caisson Guard Inspection Topside" },
    { id: "anomaly_finding", title: "Anomaly & Findings Summary" },
    { id: "incomplete", title: "Incomplete Scope Summary" },
];
