export type StructureScopeType = "ALL" | "PLATFORM" | "PIPELINE" | "SUBSEA";
export type InterfaceFileFormat = "individual_xlsx" | "individual_txt" | "individual_csv" | "single_xlsx";
export type QueryDataSourceType =
  | "STRUCTURE_SUMMARY"
  | "INSP_RECORDS"
  | "ANOMALIES"
  | "PIPE_GEO_EVENTS"
  | "COMPONENT_MASTER"
  | "JOBPACK_SOW_MASTER"
  | "ATTACHMENTS"
  | "CALIBRATION";

export interface TemplateColumn {
  key: string;
  header: string;
  dataType: "string" | "number" | "date" | "boolean";
  width: number;
  dataSize?: number;
  decSize?: number;
  sourceField?: string;
  description?: string;
  required?: boolean;
}

export interface TemplateSheet {
  id: string;
  identifierCode: string; // 3-letter SICS code, e.g. "ANS", "CPS", "GVS", "MGS"
  sheetName: string;
  fileNameFormat: string; // e.g. "yymmdd-nn-ANS.txt"
  inspectionTypeCode?: string[];
  queryStrategy: QueryDataSourceType;
  queryFilter?: Record<string, any>;
  description: string;
  columns: TemplateColumn[];
}

export interface ClientInterfaceDef {
  id: string;
  name: string;
  code: string;
  systemTitle: string;
  targetStructureType: StructureScopeType;
  defaultFileFormat: InterfaceFileFormat;
  fileNamePattern: string;
  destinationFolder: string;
  description: string;
  templates: TemplateSheet[];
}

export interface ClientProfile {
  id: string;
  code: string;
  name: string;
  fullName: string;
  country: string;
  logoColor: string;
  description: string;
  interfaces: ClientInterfaceDef[];
}

// ─── Common SICS Field Definitions ───────────────────────────────────────────
const SICS_COMMON_PREFIX: TemplateColumn[] = [
  { key: "STR_ID", header: "STR_ID", dataType: "number", width: 12, dataSize: 12, decSize: 0, description: "Structure ID (IDAMS Sequence No.)", required: true },
  { key: "TITLE", header: "TITLE", dataType: "string", width: 20, dataSize: 20, description: "Structure Title", required: true },
  { key: "PFIELD", header: "PFIELD", dataType: "string", width: 20, dataSize: 20, description: "Field Name" },
  { key: "PDESC", header: "PDESC", dataType: "string", width: 30, dataSize: 50, description: "Structure Description" },
  { key: "DEF_UNIT", header: "DEF_UNIT", dataType: "string", width: 10, dataSize: 10, description: "Structure Unit Type (Metric / Imperial)" },
  { key: "COMP_ID", header: "COMP_ID", dataType: "number", width: 12, dataSize: 12, decSize: 0, description: "Component ID", required: true },
  { key: "ID_NO", header: "ID_NO", dataType: "string", width: 20, dataSize: 25, description: "Comp. ID No. (System Generated)" },
  { key: "Q_ID", header: "Q_ID", dataType: "string", width: 16, dataSize: 16, description: "Comp. Q ID (User Generated)", required: true },
  { key: "CODE", header: "CODE", dataType: "string", width: 8, dataSize: 2, description: "Comp. Type Code" },
  { key: "COMPDESC", header: "COMPDESC", dataType: "string", width: 24, dataSize: 40, description: "Comp. Description" },
  { key: "S_NODE", header: "S_NODE", dataType: "string", width: 10, dataSize: 6, description: "Comp. Start Node" },
  { key: "F_NODE", header: "F_NODE", dataType: "string", width: 10, dataSize: 6, description: "Comp. End Node" },
  { key: "S_LEG", header: "S_LEG", dataType: "string", width: 8, dataSize: 2, description: "Comp. Start Leg" },
  { key: "F_LEG", header: "F_LEG", dataType: "string", width: 8, dataSize: 2, description: "Comp. End Leg" },
  { key: "ELV_1", header: "ELV_1", dataType: "number", width: 12, dataSize: 8, decSize: 3, description: "Comp. Start Elevation (m / ft)" },
  { key: "ELV_2", header: "ELV_2", dataType: "number", width: 12, dataSize: 8, decSize: 3, description: "Comp. End Elevation (m / ft)" },
  { key: "DIST", header: "DIST", dataType: "number", width: 10, dataSize: 6, decSize: 2, description: "Distance (m / ft)" },
  { key: "CLK_POS", header: "CLK_POS", dataType: "number", width: 10, dataSize: 4, decSize: 2, description: "Clock Position" },
  { key: "COMPTYPE", header: "COMPTYPE", dataType: "string", width: 20, dataSize: 30, description: "Component Type" },
  { key: "INSP_ID", header: "INSP_ID", dataType: "number", width: 12, dataSize: 12, decSize: 0, description: "Inspection ID", required: true },
  { key: "INSP_DATE", header: "INSP_DATE", dataType: "date", width: 14, description: "Inspection Date", required: true },
  { key: "INSP_TIME", header: "INSP_TIME", dataType: "string", width: 10, dataSize: 8, description: "Inspection Time" },
  { key: "INSPECTOR", header: "INSPECTOR", dataType: "string", width: 18, dataSize: 20, description: "Inspector Name" },
  { key: "PROC", header: "PROC", dataType: "string", width: 16, dataSize: 20, description: "Procedure Reference" },
  { key: "EQUIP", header: "EQUIP", dataType: "string", width: 16, dataSize: 20, description: "Equipment" },
  { key: "EQ_ID", header: "EQ_ID", dataType: "string", width: 16, dataSize: 20, description: "Equipment ID" },
  { key: "SPEC", header: "SPEC", dataType: "string", width: 16, dataSize: 20, description: "Specification" },
  { key: "SURF_COND", header: "SURF_COND", dataType: "string", width: 18, dataSize: 30, description: "Surface Condition" },
  { key: "CLEAN_MET", header: "CLEAN_MET", dataType: "string", width: 16, dataSize: 20, description: "Cleaning Method" },
  { key: "SCAF", header: "SCAF", dataType: "string", width: 8, dataSize: 3, description: "Scaffolding (Yes/No)" },
  { key: "SUPV", header: "SUPV", dataType: "string", width: 16, dataSize: 20, description: "Supervisor Name" },
  { key: "DIVR", header: "DIVR", dataType: "string", width: 16, dataSize: 20, description: "Diver / ROV Name" },
  { key: "DIVE_NO", header: "DIVE_NO", dataType: "string", width: 12, dataSize: 10, description: "Diver No. / Dive Log No." },
  { key: "ELEVATION", header: "ELEVATION", dataType: "number", width: 12, dataSize: 9, decSize: 3, description: "Comp. Elevation (m / ft)" },
  { key: "TOP_UND", header: "TOP_UND", dataType: "string", width: 12, dataSize: 8, description: "Topside or Underwater" },
];

const SICS_COMMON_SUFFIX: TemplateColumn[] = [
  { key: "DEFECT", header: "DEFECT", dataType: "string", width: 8, dataSize: 3, description: "Defect Present? (Yes/No)" },
  { key: "DFT_CODE_TYPE", header: "DFT_CODE_TYPE", dataType: "string", width: 14, dataSize: 12, description: "Defect Code Type (AW, DB, PD, etc.)" },
  { key: "DEFECT_CODE", header: "DEFECT_CODE", dataType: "string", width: 18, dataSize: 50, description: "Defect Code" },
  { key: "DEFECT_TYPE", header: "DEFECT_TYPE", dataType: "string", width: 16, dataSize: 20, description: "Defect Rating" },
  { key: "DEFECT_DESC", header: "DEFECT_DESC", dataType: "string", width: 30, dataSize: 250, description: "Defect Comments" },
  { key: "DFT_REF_NO", header: "DFT_REF_NO", dataType: "string", width: 18, dataSize: 30, description: "Defect Reference No." },
  { key: "RECTIFID", header: "RECTIFID", dataType: "string", width: 10, dataSize: 3, description: "Defect Rectified? (Yes/No)" },
  { key: "RECTIFID_DESC", header: "RECTIFID_DESC", dataType: "string", width: 28, dataSize: 250, description: "Rectified Comments" },
  { key: "RECT_DATE", header: "RECT_DATE", dataType: "date", width: 14, description: "Rectified Date" },
  { key: "INSPNO", header: "INSPNO", dataType: "string", width: 16, dataSize: 11, description: "Inspection / SOW Report No.", required: true },
  { key: "JOBNAME", header: "JOBNAME", dataType: "string", width: 20, dataSize: 20, description: "SOW / Jobpack Name", required: true },
  { key: "STATUS", header: "STATUS", dataType: "string", width: 12, dataSize: 10, description: "SOW/Jobpack Status (OPEN / CLOSED)" },
  { key: "INSP_DONE", header: "INSP_DONE", dataType: "string", width: 10, dataSize: 3, description: "Inspection Done (Yes/No)" },
  { key: "REC_DATE", header: "REC_DATE", dataType: "date", width: 14, description: "Record Last Modified Date" },
  { key: "INSP_COND", header: "INSP_COND", dataType: "string", width: 40, dataSize: 1000, description: "Findings (Single-line space separated)" },
  { key: "CMNTS", header: "CMNTS", dataType: "string", width: 40, dataSize: 4000, description: "Comments (Single-line space separated)" },
  { key: "JOB_TYPE", header: "JOB_TYPE", dataType: "string", width: 16, dataSize: 20, description: "Job/Scope Type (MAJOR, PARTIAL, SPECIAL, PIPELINE)" },
  { key: "LAST_MAJOR_INSPNO", header: "LAST_MAJOR_INSPNO", dataType: "string", width: 18, dataSize: 11, description: "Last Major Inspection No." },
  { key: "INSPTYPE", header: "INSPTYPE", dataType: "string", width: 10, dataSize: 3, description: "Inspection Type Identifier Code" },
  { key: "EVAL_BY", header: "EVAL_BY", dataType: "string", width: 20, dataSize: 250, description: "Anomaly Rectification Evaluated By" },
  { key: "APPROV_BY", header: "APPROV_BY", dataType: "string", width: 20, dataSize: 250, description: "Anomaly Rectification Approved By" },
];

// ─── 24 Official PCSB SICS Interface Templates ──────────────────────────────
export const PCSB_SICS_TEMPLATES: TemplateSheet[] = [
  // 1. ANS - Anode Inspection
  {
    id: "sics-ans",
    identifierCode: "ANS",
    sheetName: "ANS_ANODE",
    fileNameFormat: "yymmdd-nn-ANS.txt",
    queryStrategy: "INSP_RECORDS",
    inspectionTypeCode: ["ANMIN", "ANODE", "CPINS"],
    description: "Anode Inspection & Depletion Table Structure",
    columns: [
      ...SICS_COMMON_PREFIX,
      { key: "CP_RDG", header: "CP_RDG", dataType: "number", width: 12, dataSize: 7, description: "CP Stab Reading (mA)" },
      { key: "ANODE_OUTPUT", header: "ANODE_OUTPUT", dataType: "number", width: 14, dataSize: 5, decSize: 0, description: "Anode CP (mV)" },
      { key: "MG_THICK", header: "MG_THICK", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "Marine Growth Thickness (mm/in)" },
      { key: "MEMB_CP", header: "MEMB_CP", dataType: "number", width: 12, dataSize: 5, description: "Member CP (mV)" },
      { key: "LENGTH", header: "LENGTH", dataType: "number", width: 12, dataSize: 9, decSize: 3, description: "Length (mm/in)" },
      { key: "CIRC_C1", header: "CIRC_C1", dataType: "string", width: 12, dataSize: 20, description: "Circumference C1" },
      { key: "CIRC_C2", header: "CIRC_C2", dataType: "string", width: 12, dataSize: 20, description: "Circumference C2" },
      { key: "CIRC_C3", header: "CIRC_C3", dataType: "string", width: 12, dataSize: 20, description: "Circumference C3" },
      { key: "TYPE", header: "TYPE", dataType: "string", width: 14, dataSize: 20, description: "Anode Type" },
      { key: "SECURED", header: "SECURED", dataType: "string", width: 10, dataSize: 3, description: "Secured / Connected (Yes/No)" },
      { key: "DEPLETION", header: "DEPLETION", dataType: "number", width: 12, dataSize: 6, decSize: 2, description: "Depletion Percentage (%)" },
      { key: "TOPSTUB_CP", header: "TOPSTUB_CP", dataType: "number", width: 12, dataSize: 5, description: "Top Stub CP (mV)" },
      { key: "BOTSTUB_CP", header: "BOTSTUB_CP", dataType: "number", width: 12, dataSize: 5, description: "Bottom Stub CP (mV)" },
      { key: "AVG_PIT", header: "AVG_PIT", dataType: "number", width: 12, dataSize: 5, description: "Average Pitting Depth (mm/in)" },
      { key: "MAX_PIT", header: "MAX_PIT", dataType: "number", width: 12, dataSize: 5, description: "Maximum Pitting Depth (mm/in)" },
      { key: "AVG_DIA_PIT", header: "AVG_DIA_PIT", dataType: "number", width: 14, dataSize: 5, description: "Average Pitting Diameter (mm/in)" },
      { key: "MAX_DIA_PIT", header: "MAX_DIA_PIT", dataType: "number", width: 14, dataSize: 5, description: "Maximum Pitting Diameter (mm/in)" },
      ...SICS_COMMON_SUFFIX,
    ],
  },

  // 2. CPS - CP Survey
  {
    id: "sics-cps",
    identifierCode: "CPS",
    sheetName: "CPS_CP_SURVEY",
    fileNameFormat: "yymmdd-nn-CPS.txt",
    queryStrategy: "INSP_RECORDS",
    inspectionTypeCode: ["CPCLB", "CPINS", "PIPECP"],
    description: "Cathodic Protection Survey Table Structure",
    columns: [
      ...SICS_COMMON_PREFIX,
      { key: "CALIB_BLK", header: "CALIB_BLK", dataType: "string", width: 16, dataSize: 20, description: "Calibration Block" },
      { key: "PRE_DIV", header: "PRE_DIV", dataType: "number", width: 12, dataSize: 5, decSize: 0, description: "Pre Dive reading (mV)" },
      { key: "IN_WATER1", header: "IN_WATER1", dataType: "number", width: 12, dataSize: 5, decSize: 0, description: "In Water 1 (mV)" },
      { key: "IN_WATER2", header: "IN_WATER2", dataType: "number", width: 12, dataSize: 5, decSize: 0, description: "In Water 2 (mV)" },
      { key: "IN_WATER3", header: "IN_WATER3", dataType: "number", width: 12, dataSize: 5, decSize: 0, description: "In Water 3 (mV)" },
      { key: "POST_DIVE", header: "POST_DIVE", dataType: "number", width: 12, dataSize: 5, decSize: 0, description: "Post Dive Reading (mV)" },
      { key: "CP_IN", header: "CP_IN", dataType: "number", width: 12, dataSize: 5, decSize: 0, description: "CP In (mV)" },
      { key: "CP_OUT", header: "CP_OUT", dataType: "number", width: 12, dataSize: 5, decSize: 0, description: "CP Out (mV)" },
      ...SICS_COMMON_SUFFIX,
    ],
  },

  // 3. GVS - General Visual Inspection
  {
    id: "sics-gvs",
    identifierCode: "GVS",
    sheetName: "GVS_GENERAL_VISUAL",
    fileNameFormat: "yymmdd-nn-GVS.txt",
    queryStrategy: "INSP_RECORDS",
    inspectionTypeCode: ["GVI", "GENIN"],
    description: "General Visual Inspection Table Structure",
    columns: [
      ...SICS_COMMON_PREFIX,
      { key: "COAT_COND", header: "COAT_COND", dataType: "string", width: 16, dataSize: 20, description: "Coating Condition" },
      { key: "COMP_COND", header: "COMP_COND", dataType: "string", width: 18, dataSize: 20, description: "Component Condition" },
      { key: "MARINE_GROW", header: "MARINE_GROW", dataType: "number", width: 14, dataSize: 3, description: "Marine Growth %" },
      ...SICS_COMMON_SUFFIX,
    ],
  },

  // 4. MGS - Marine Growth Inspection
  {
    id: "sics-mgs",
    identifierCode: "MGS",
    sheetName: "MGS_MARINE_GROWTH",
    fileNameFormat: "yymmdd-nn-MGS.txt",
    queryStrategy: "INSP_RECORDS",
    inspectionTypeCode: ["MGINS", "MGCLB"],
    description: "Marine Growth Inspection Table Structure",
    columns: [
      ...SICS_COMMON_PREFIX,
      { key: "CP_RDG", header: "CP_RDG", dataType: "number", width: 12, dataSize: 7, decSize: 0, description: "CP Reading" },
      { key: "HARD_GROWTH", header: "HARD_GROWTH", dataType: "number", width: 14, dataSize: 3, decSize: 0, description: "Hard Growth %" },
      { key: "SOFT_GROWTH", header: "SOFT_GROWTH", dataType: "number", width: 14, dataSize: 3, decSize: 0, description: "Soft Growth %" },
      { key: "COATING_DAMAGE", header: "COATING_DAMAGE", dataType: "string", width: 14, dataSize: 3, description: "Coating Damage (Yes/No)" },
      { key: "PHYSICAL_DAMAGE", header: "PHYSICAL_DAMAGE", dataType: "string", width: 14, dataSize: 3, description: "Physical Damage (Yes/No)" },
      { key: "HARD_THK3", header: "HARD_THK3", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "Hard Thickness 3 o'clock (mm/in)" },
      { key: "HARD_THK6", header: "HARD_THK6", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "Hard Thickness 6 o'clock (mm/in)" },
      { key: "HARD_THK9", header: "HARD_THK9", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "Hard Thickness 9 o'clock (mm/in)" },
      { key: "HARD_THK12", header: "HARD_THK12", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "Hard Thickness 12 o'clock (mm/in)" },
      { key: "SOFT_THK3", header: "SOFT_THK3", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "Soft Thickness 3 o'clock (mm/in)" },
      { key: "SOFT_THK6", header: "SOFT_THK6", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "Soft Thickness 6 o'clock (mm/in)" },
      { key: "SOFT_THK9", header: "SOFT_THK9", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "Soft Thickness 9 o'clock (mm/in)" },
      { key: "SOFT_THK12", header: "SOFT_THK12", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "Soft Thickness 12 o'clock (mm/in)" },
      { key: "CIRCUM_PFIVE", header: "CIRCUM_PFIVE", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "Circumferential Meas. +ve5 (mm/in)" },
      { key: "CIRCUM_NFIVE", header: "CIRCUM_NFIVE", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "Circumferential Meas. -ve5 (mm/in)" },
      { key: "CIRCUM_ZERO", header: "CIRCUM_ZERO", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "Circumferential Meas. 0 (mm/in)" },
      { key: "NOM_DIA", header: "NOM_DIA", dataType: "number", width: 12, dataSize: 9, decSize: 3, description: "Leg Nominal Diameter (mm/in)" },
      { key: "HARD_CIRCUM", header: "HARD_CIRCUM", dataType: "string", width: 12, dataSize: 3, description: "Hard? (Yes/No)" },
      { key: "SOFT_CIRCUM", header: "SOFT_CIRCUM", dataType: "string", width: 12, dataSize: 3, description: "Soft? (Yes/No)" },
      { key: "GROWTH_CIRCUM", header: "GROWTH_CIRCUM", dataType: "number", width: 14, dataSize: 3, description: "Growth %" },
      { key: "EFF_THK", header: "EFF_THK", dataType: "number", width: 12, dataSize: 9, decSize: 3, description: "Effective Thickness (mm/in)" },
      { key: "MG_PROFILE", header: "MG_PROFILE", dataType: "number", width: 14, dataSize: 4, decSize: 0, description: "Maximum Allowable Thickness (mm/in)" },
      ...SICS_COMMON_SUFFIX,
    ],
  },

  // 5. SCS - Scour Survey
  {
    id: "sics-scs",
    identifierCode: "SCS",
    sheetName: "SCS_SCOUR_SURVEY",
    fileNameFormat: "yymmdd-nn-SCS.txt",
    queryStrategy: "INSP_RECORDS",
    inspectionTypeCode: ["SCR", "SCOUR"],
    description: "Scour Inspection Table Structure",
    columns: [
      ...SICS_COMMON_PREFIX,
      { key: "FRAME_RDG", header: "FRAME_RDG", dataType: "number", width: 12, dataSize: 9, decSize: 3, description: "Mud Mat Height (m/ft)" },
      { key: "BOTTM_RDG", header: "BOTTM_RDG", dataType: "number", width: 12, dataSize: 9, decSize: 3, description: "Bottom Reading" },
      { key: "SCOUR_RDG", header: "SCOUR_RDG", dataType: "number", width: 12, dataSize: 9, decSize: 3, description: "Scour Reading" },
      { key: "SCOUR_SIZE", header: "SCOUR_SIZE", dataType: "string", width: 14, dataSize: 20, description: "Scour Size" },
      { key: "MID_POINT", header: "MID_POINT", dataType: "number", width: 12, dataSize: 9, decSize: 3, description: "Mid Point (m/ft)" },
      { key: "LEG1", header: "LEG1", dataType: "string", width: 12, dataSize: 20, description: "Leg 1" },
      { key: "LEG2", header: "LEG2", dataType: "string", width: 12, dataSize: 20, description: "Leg 2" },
      { key: "EXP_PILE_LEG1", header: "EXP_PILE_LEG1", dataType: "string", width: 14, dataSize: 3, description: "Exposed Pile Leg 1 (Yes/No)" },
      { key: "EXP_PILE_LEG2", header: "EXP_PILE_LEG2", dataType: "string", width: 14, dataSize: 3, description: "Exposed Pile Leg 2 (Yes/No)" },
      { key: "DEPTH1", header: "DEPTH1", dataType: "number", width: 12, dataSize: 9, decSize: 3, description: "Depth 1 (m/ft)" },
      { key: "DEPTH2", header: "DEPTH2", dataType: "number", width: 12, dataSize: 9, decSize: 3, description: "Depth 2 (m/ft)" },
      ...SICS_COMMON_SUFFIX,
    ],
  },

  // 6. DBS - Debris Inspection
  {
    id: "sics-dbs",
    identifierCode: "DBS",
    sheetName: "DBS_DEBRIS",
    fileNameFormat: "yymmdd-nn-DBS.txt",
    queryStrategy: "INSP_RECORDS",
    inspectionTypeCode: ["DEBRIS", "DBS"],
    description: "Debris Table Structure",
    columns: [
      ...SICS_COMMON_PREFIX,
      { key: "CP_RDG", header: "CP_RDG", dataType: "number", width: 12, dataSize: 7, decSize: 0, description: "CP Reading (mV)" },
      { key: "SIDE", header: "SIDE", dataType: "string", width: 12, dataSize: 20, description: "Side" },
      { key: "DISTANC", header: "DISTANC", dataType: "number", width: 12, dataSize: 9, decSize: 3, description: "Distance of Debris (m/ft)" },
      { key: "CP_CURR", header: "CP_CURR", dataType: "string", width: 14, dataSize: 3, description: "Debris Pulling CP Current (Yes/No)" },
      { key: "DAMAGE", header: "DAMAGE", dataType: "string", width: 12, dataSize: 3, description: "Damage Caused (Yes/No)" },
      { key: "REMOVED", header: "REMOVED", dataType: "string", width: 12, dataSize: 3, description: "Debris Removed (Yes/No)" },
      { key: "LENGTH", header: "LENGTH", dataType: "number", width: 12, dataSize: 6, decSize: 0, description: "Length (mm/in)" },
      { key: "HEIGHT", header: "HEIGHT", dataType: "number", width: 12, dataSize: 6, decSize: 0, description: "Height (mm/in)" },
      { key: "WIDTH", header: "WIDTH", dataType: "number", width: 12, dataSize: 6, decSize: 0, description: "Width (mm/in)" },
      { key: "ITEM", header: "ITEM", dataType: "string", width: 16, dataSize: 20, description: "Debris Item" },
      { key: "SIZE", header: "SIZE", dataType: "string", width: 14, dataSize: 20, description: "Size" },
      { key: "ASSESSMENT", header: "ASSESSMENT", dataType: "string", width: 24, dataSize: 60, description: "Assessment" },
      ...SICS_COMMON_SUFFIX,
    ],
  },

  // 7. FDS - Flooded Member Survey
  {
    id: "sics-fds",
    identifierCode: "FDS",
    sheetName: "FDS_FLOODED_MEMBER",
    fileNameFormat: "yymmdd-nn-FDS.txt",
    queryStrategy: "INSP_RECORDS",
    inspectionTypeCode: ["FMD", "FLOOD"],
    description: "Flooded Member Table Structure",
    columns: [
      ...SICS_COMMON_PREFIX,
      { key: "FLOODED", header: "FLOODED", dataType: "string", width: 12, dataSize: 3, description: "Member Flooded? (Yes/No)" },
      ...SICS_COMMON_SUFFIX,
    ],
  },

  // 8. UTS - UT Wall Thickness Inspection
  {
    id: "sics-uts",
    identifierCode: "UTS",
    sheetName: "UTS_WALL_THICKNESS",
    fileNameFormat: "yymmdd-nn-UTS.txt",
    queryStrategy: "INSP_RECORDS",
    inspectionTypeCode: ["UTCLB", "UTINS", "WTINS"],
    description: "UT Wall Thickness Inspection Table Structure",
    columns: [
      ...SICS_COMMON_PREFIX,
      { key: "PROB_TYPE", header: "PROB_TYPE", dataType: "string", width: 14, dataSize: 20, description: "Probe Type" },
      { key: "PROB_SIZE_DIAM", header: "PROB_SIZE_DIAM", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "Probe Size/Diameter (mm/in)" },
      { key: "SCAN_TECH", header: "SCAN_TECH", dataType: "string", width: 14, dataSize: 20, description: "Scanning Tech" },
      { key: "COUPLANT", header: "COUPLANT", dataType: "string", width: 14, dataSize: 20, description: "Couplant" },
      { key: "CALIB_BLK", header: "CALIB_BLK", dataType: "string", width: 16, dataSize: 20, description: "Calibration Block" },
      { key: "CALIB_RANGE", header: "CALIB_RANGE", dataType: "string", width: 14, dataSize: 20, description: "Calibration Range" },
      { key: "CALIB_DATE", header: "CALIB_DATE", dataType: "date", width: 14, description: "Calibration Date" },
      { key: "PROB_FREQ", header: "PROB_FREQ", dataType: "number", width: 12, dataSize: 9, decSize: 3, description: "Probe Frequency (Hertz)" },
      { key: "SENS_LVL", header: "SENS_LVL", dataType: "string", width: 14, dataSize: 20, description: "Sensitivity Level" },
      { key: "AREA_TEST", header: "AREA_TEST", dataType: "string", width: 14, dataSize: 20, description: "Area Tested" },
      { key: "REF_POS", header: "REF_POS", dataType: "string", width: 14, dataSize: 20, description: "Reference Point Position" },
      { key: "COMP_WALL_THK", header: "COMP_WALL_THK", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "Comp. Wall Thickness (mm/in)" },
      { key: "MAX_THK", header: "MAX_THK", dataType: "number", width: 12, dataSize: 9, decSize: 3, description: "Maximum Thickness (mm/in)" },
      { key: "MIN_THK", header: "MIN_THK", dataType: "number", width: 12, dataSize: 9, decSize: 3, description: "Minimum Thickness (mm/in)" },
      { key: "AVG_THK", header: "AVG_THK", dataType: "number", width: 12, dataSize: 9, decSize: 3, description: "Average Thickness (mm/in)" },
      { key: "WALL_THK_LOSS", header: "WALL_THK_LOSS", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "Wall Thickness Loss (mm/in)" },
      { key: "CORR_RATE", header: "CORR_RATE", dataType: "number", width: 12, dataSize: 9, decSize: 3, description: "Corrosion Rate (mpy)" },
      { key: "NO_READINGS", header: "NO_READINGS", dataType: "number", width: 12, dataSize: 3, decSize: 0, description: "No. of Readings" },
      { key: "C01", header: "C01", dataType: "number", width: 10, dataSize: 9, decSize: 3, description: "1 O'Clock (mm/in)" },
      { key: "C02", header: "C02", dataType: "number", width: 10, dataSize: 9, decSize: 3, description: "2 O'Clock (mm/in)" },
      { key: "C03", header: "C03", dataType: "number", width: 10, dataSize: 9, decSize: 3, description: "3 O'Clock (mm/in)" },
      { key: "C04", header: "C04", dataType: "number", width: 10, dataSize: 9, decSize: 3, description: "4 O'Clock (mm/in)" },
      { key: "C05", header: "C05", dataType: "number", width: 10, dataSize: 9, decSize: 3, description: "5 O'Clock (mm/in)" },
      { key: "C06", header: "C06", dataType: "number", width: 10, dataSize: 9, decSize: 3, description: "6 O'Clock (mm/in)" },
      { key: "C07", header: "C07", dataType: "number", width: 10, dataSize: 9, decSize: 3, description: "7 O'Clock (mm/in)" },
      { key: "C08", header: "C08", dataType: "number", width: 10, dataSize: 9, decSize: 3, description: "8 O'Clock (mm/in)" },
      { key: "C09", header: "C09", dataType: "number", width: 10, dataSize: 9, decSize: 3, description: "9 O'Clock (mm/in)" },
      { key: "C10", header: "C10", dataType: "number", width: 10, dataSize: 9, decSize: 3, description: "10 O'Clock (mm/in)" },
      { key: "C11", header: "C11", dataType: "number", width: 10, dataSize: 9, decSize: 3, description: "11 O'Clock (mm/in)" },
      { key: "C12", header: "C12", dataType: "number", width: 10, dataSize: 9, decSize: 3, description: "12 O'Clock (mm/in)" },
      { key: "REF_NAME", header: "REF_NAME", dataType: "string", width: 14, dataSize: 20, description: "Reference Name" },
      { key: "POSITION", header: "POSITION", dataType: "string", width: 14, dataSize: 20, description: "Position" },
      { key: "READ_THICK", header: "READ_THICK", dataType: "number", width: 12, dataSize: 9, decSize: 3, description: "Read Thickness" },
      ...SICS_COMMON_SUFFIX,
    ],
  },

  // 9. VDS - Video Inspection
  {
    id: "sics-vds",
    identifierCode: "VDS",
    sheetName: "VDS_VIDEO",
    fileNameFormat: "yymmdd-nn-VDS.txt",
    queryStrategy: "INSP_RECORDS",
    inspectionTypeCode: ["VIDEO", "VDS"],
    description: "Video Inspection Table Structure",
    columns: [
      ...SICS_COMMON_PREFIX,
      { key: "LIGHT_METHOD", header: "LIGHT_METHOD", dataType: "string", width: 14, dataSize: 20, description: "Lighting Method" },
      { key: "TAPE_TYPE", header: "TAPE_TYPE", dataType: "string", width: 14, dataSize: 20, description: "Tape Type/Format" },
      { key: "TAPE_NO", header: "TAPE_NO", dataType: "string", width: 14, dataSize: 20, description: "Tape No." },
      { key: "SUBJECT", header: "SUBJECT", dataType: "string", width: 18, dataSize: 30, description: "Subject" },
      { key: "TAPE_FOOTAGE", header: "TAPE_FOOTAGE", dataType: "string", width: 16, dataSize: 30, description: "Tape Footage / Counters" },
      { key: "TAPE_PERMIT_ISSUE_DATE", header: "TAPE_PERMIT_ISSUE_DATE", dataType: "date", width: 16, description: "Permit Issued Date" },
      ...SICS_COMMON_SUFFIX,
    ],
  },

  // 10. PHS - Photography
  {
    id: "sics-phs",
    identifierCode: "PHS",
    sheetName: "PHS_PHOTO",
    fileNameFormat: "yymmdd-nn-PHS.txt",
    queryStrategy: "INSP_RECORDS",
    inspectionTypeCode: ["PHOTO", "PHS"],
    description: "Photo Inspection Table Structure",
    columns: [
      ...SICS_COMMON_PREFIX,
      { key: "LIGHT_METHOD", header: "LIGHT_METHOD", dataType: "string", width: 14, dataSize: 20, description: "Lighting Method" },
      { key: "FILM_TYPE", header: "FILM_TYPE", dataType: "string", width: 14, dataSize: 20, description: "Film Type" },
      { key: "DESCRIPTION", header: "DESCRIPTION", dataType: "string", width: 24, dataSize: 50, description: "Description" },
      { key: "WRK_PERMIT_ISSUE_DATE", header: "WRK_PERMIT_ISSUE_DATE", dataType: "date", width: 16, description: "Work Permit Issued Date" },
      { key: "EXPOSURE_NO", header: "EXPOSURE_NO", dataType: "number", width: 12, dataSize: 2, description: "Exposure No." },
      { key: "SUBJECT", header: "SUBJECT", dataType: "string", width: 18, dataSize: 30, description: "Subject" },
      { key: "FILM_NO", header: "FILM_NO", dataType: "string", width: 14, dataSize: 20, description: "Film No." },
      { key: "FILM_SPEED", header: "FILM_SPEED", dataType: "string", width: 12, dataSize: 10, description: "Film Speed" },
      { key: "CAMERA_TYP", header: "CAMERA_TYP", dataType: "string", width: 14, dataSize: 20, description: "Camera Type" },
      { key: "LENS", header: "LENS", dataType: "string", width: 12, dataSize: 10, description: "Lens" },
      { key: "SNAP", header: "SNAP", dataType: "string", width: 12, dataSize: 10, description: "Snap" },
      { key: "PHOTO_NO", header: "PHOTO_NO", dataType: "string", width: 12, dataSize: 10, description: "Photo No." },
      { key: "FILM_REF", header: "FILM_REF", dataType: "string", width: 14, dataSize: 20, description: "Film Reference" },
      ...SICS_COMMON_SUFFIX,
    ],
  },

  // 11. MPS - Magnetic Particle Inspection
  {
    id: "sics-mps",
    identifierCode: "MPS",
    sheetName: "MPS_MPI",
    fileNameFormat: "yymmdd-nn-MPS.txt",
    queryStrategy: "INSP_RECORDS",
    inspectionTypeCode: ["MPI", "MPS", "MAG"],
    description: "Magnetic Particle Inspection Table Structure",
    columns: [
      ...SICS_COMMON_PREFIX,
      { key: "CALIB_BLK", header: "CALIB_BLK", dataType: "string", width: 16, dataSize: 20, description: "Calibration Block" },
      { key: "MAGNT_INK", header: "MAGNT_INK", dataType: "string", width: 14, dataSize: 20, description: "Magnetic Ink" },
      { key: "MAGNT_METHOD", header: "MAGNT_METHOD", dataType: "string", width: 14, dataSize: 20, description: "Magnetic Method" },
      { key: "BAKGD_CONT", header: "BAKGD_CONT", dataType: "string", width: 14, dataSize: 20, description: "Background Contrast" },
      { key: "MAGNT_LIFT_POWER", header: "MAGNT_LIFT_POWER", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "Magnetic Lifting Power (tonne/pound)" },
      { key: "ORIENTATION", header: "ORIENTATION", dataType: "string", width: 14, dataSize: 20, description: "Orientation" },
      { key: "LIGHT_METHOD", header: "LIGHT_METHOD", dataType: "string", width: 14, dataSize: 20, description: "Lighting Method" },
      { key: "CURR_COIL_MAGN", header: "CURR_COIL_MAGN", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "Current in Coil/Magnet (Amps)" },
      { key: "VOLT_COIL_MAGN", header: "VOLT_COIL_MAGN", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "Volt in Coil/Magnet (Volts)" },
      { key: "MAGN_CURR_POLE", header: "MAGN_CURR_POLE", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "Current Pole Spacing (mm/in)" },
      { key: "DEMAGN", header: "DEMAGN", dataType: "string", width: 12, dataSize: 3, description: "Demagnetized (Yes/No)" },
      { key: "DISTANCE", header: "DISTANCE", dataType: "number", width: 12, dataSize: 9, decSize: 3, description: "Distance from Datum" },
      { key: "INDICATION", header: "INDICATION", dataType: "string", width: 14, dataSize: 20, description: "Indication" },
      { key: "SIZE", header: "SIZE", dataType: "string", width: 12, dataSize: 20, description: "Size" },
      { key: "BURMAH", header: "BURMAH", dataType: "string", width: 14, dataSize: 20, description: "Burmah C Strip" },
      { key: "PROBE_FL", header: "PROBE_FL", dataType: "string", width: 14, dataSize: 20, description: "Probe" },
      { key: "WALL_THK3", header: "WALL_THK3", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "Brace 3 O'Clock Wall Thick" },
      { key: "WALL_THK6", header: "WALL_THK6", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "Brace 6 O'Clock Wall Thick" },
      { key: "WALL_THK9", header: "WALL_THK9", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "Brace 9 O'Clock Wall Thick" },
      { key: "WALL_THK12", header: "WALL_THK12", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "Brace 12 O'Clock Wall Thick" },
      { key: "C_WALL_THK3", header: "C_WALL_THK3", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "Chord 3 O'Clock Wall Thick" },
      { key: "C_WALL_THK6", header: "C_WALL_THK6", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "Chord 6 O'Clock Wall Thick" },
      { key: "C_WALL_THK9", header: "C_WALL_THK9", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "Chord 9 O'Clock Wall Thick" },
      { key: "C_WALL_THK12", header: "C_WALL_THK12", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "Chord 12 O'Clock Wall Thick" },
      { key: "T_CHORD1", header: "T_CHORD1", dataType: "string", width: 18, dataSize: 50, description: "Toe-Chord 6-9" },
      { key: "T_CHORD2", header: "T_CHORD2", dataType: "string", width: 18, dataSize: 50, description: "Toe-Chord 9-12" },
      { key: "T_CHORD3", header: "T_CHORD3", dataType: "string", width: 18, dataSize: 50, description: "Toe-Chord 12-3" },
      { key: "T_CHORD4", header: "T_CHORD4", dataType: "string", width: 18, dataSize: 50, description: "Toe-Chord 3-6" },
      { key: "WELD1", header: "WELD1", dataType: "string", width: 18, dataSize: 50, description: "Weld 6-9" },
      { key: "WELD2", header: "WELD2", dataType: "string", width: 18, dataSize: 50, description: "Weld 9-12" },
      { key: "WELD3", header: "WELD3", dataType: "string", width: 18, dataSize: 50, description: "Weld 12-3" },
      { key: "WELD4", header: "WELD4", dataType: "string", width: 18, dataSize: 50, description: "Weld 3-6" },
      { key: "T_BRACE1", header: "T_BRACE1", dataType: "string", width: 18, dataSize: 50, description: "Toe-Brace 6-9" },
      { key: "T_BRACE2", header: "T_BRACE2", dataType: "string", width: 18, dataSize: 50, description: "Toe-Brace 9-12" },
      { key: "T_BRACE3", header: "T_BRACE3", dataType: "string", width: 18, dataSize: 50, description: "Toe-Brace 12-3" },
      { key: "T_BRACE4", header: "T_BRACE4", dataType: "string", width: 18, dataSize: 50, description: "Toe-Brace 3-6" },
      { key: "CP_WALL_THK3", header: "CP_WALL_THK3", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "CP Wall Thick 3 O'Clock (mV)" },
      { key: "CP_WALL_THK6", header: "CP_WALL_THK6", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "CP Wall Thick 6 O'Clock (mV)" },
      { key: "CP_WALL_THK9", header: "CP_WALL_THK9", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "CP Wall Thick 9 O'Clock (mV)" },
      { key: "CP_WALL_THK12", header: "CP_WALL_THK12", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "CP Wall Thick 12 O'Clock (mV)" },
      { key: "SPEC_THK_CHORD", header: "SPEC_THK_CHORD", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "Chord Specified Thick (mm/in)" },
      { key: "SPEC_THK_BRACE", header: "SPEC_THK_BRACE", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "Brace Specified Thick (mm/in)" },
      { key: "POSITION", header: "POSITION", dataType: "string", width: 14, dataSize: 20, description: "Position" },
      { key: "UTWT", header: "UTWT", dataType: "number", width: 12, dataSize: 9, decSize: 3, description: "UT Wall Thickness (mm/in)" },
      { key: "UNDERCUT", header: "UNDERCUT", dataType: "number", width: 12, dataSize: 9, decSize: 3, description: "Undercut (mm/in)" },
      ...SICS_COMMON_SUFFIX,
    ],
  },

  // 12. CCS - CP Calibration
  {
    id: "sics-ccs",
    identifierCode: "CCS",
    sheetName: "CCS_CP_CALIBRATION",
    fileNameFormat: "yymmdd-nn-CCS.txt",
    queryStrategy: "CALIBRATION",
    inspectionTypeCode: ["CPCLB", "CCS"],
    description: "CP Calibration Inspection Table Structure",
    columns: [
      ...SICS_COMMON_PREFIX,
      { key: "CLB_BLOCK", header: "CLB_BLOCK", dataType: "string", width: 16, dataSize: 20, description: "Calibration Block" },
      { key: "PRE_DIVE", header: "PRE_DIVE", dataType: "number", width: 12, dataSize: 9, decSize: 3, description: "Pre Dive (mV)" },
      { key: "IN_WATER1", header: "IN_WATER1", dataType: "number", width: 12, dataSize: 9, decSize: 3, description: "In Water 1 (mV)" },
      { key: "IN_WATER2", header: "IN_WATER2", dataType: "number", width: 12, dataSize: 9, decSize: 3, description: "In Water 2 (mV)" },
      { key: "IN_WATER3", header: "IN_WATER3", dataType: "number", width: 12, dataSize: 9, decSize: 3, description: "In Water 3 (mV)" },
      { key: "POST_DIVE", header: "POST_DIVE", dataType: "number", width: 12, dataSize: 9, decSize: 3, description: "Post Dive (mV)" },
      { key: "INSPNO", header: "INSPNO", dataType: "string", width: 16, dataSize: 11, description: "Inspection No", required: true },
      { key: "JOBNAME", header: "JOBNAME", dataType: "string", width: 20, dataSize: 20, description: "SOW/Jobpack Name", required: true },
      { key: "STATUS", header: "STATUS", dataType: "string", width: 12, dataSize: 10, description: "SOW/Jobpack Status (OPEN / CLOSED)" },
      { key: "REC_DATE", header: "REC_DATE", dataType: "date", width: 14, description: "Modified Date" },
      { key: "INSP_COND", header: "INSP_COND", dataType: "string", width: 40, dataSize: 1000, description: "Findings" },
      { key: "CMNTS", header: "CMNTS", dataType: "string", width: 40, dataSize: 4000, description: "Comments" },
    ],
  },

  // 13. RSS - Riser Survey
  {
    id: "sics-rss",
    identifierCode: "RSS",
    sheetName: "RSS_RISER_SURVEY",
    fileNameFormat: "yymmdd-nn-RSS.txt",
    queryStrategy: "INSP_RECORDS",
    inspectionTypeCode: ["RISER", "RSS"],
    description: "Riser Survey Table Structure",
    columns: [
      ...SICS_COMMON_PREFIX,
      { key: "CP_RDG", header: "CP_RDG", dataType: "number", width: 12, dataSize: 7, decSize: 0, description: "CP Reading" },
      { key: "RISER_PRES", header: "RISER_PRES", dataType: "string", width: 12, dataSize: 3, description: "Riser Present (Yes/No)" },
      { key: "TYPE", header: "TYPE", dataType: "string", width: 14, dataSize: 20, description: "Type" },
      { key: "DIAMETER", header: "DIAMETER", dataType: "number", width: 12, dataSize: 9, decSize: 3, description: "Diameter" },
      { key: "WALL_THK", header: "WALL_THK", dataType: "number", width: 12, dataSize: 9, decSize: 3, description: "Wall Thickness" },
      { key: "COAT_TYP", header: "COAT_TYP", dataType: "string", width: 14, dataSize: 20, description: "Coating Type" },
      { key: "MG", header: "MG", dataType: "string", width: 14, dataSize: 25, description: "Marine Growth" },
      { key: "BOTTM_HT", header: "BOTTM_HT", dataType: "number", width: 12, dataSize: 9, decSize: 3, description: "Span Height" },
      { key: "ELEV_BOTTM", header: "ELEV_BOTTM", dataType: "number", width: 12, dataSize: 9, decSize: 3, description: "J-Tube Elevation" },
      { key: "KNEE_BRACE", header: "KNEE_BRACE", dataType: "string", width: 12, dataSize: 3, description: "Knee Brace (Yes/No)" },
      { key: "SUPP_BEAM", header: "SUPP_BEAM", dataType: "string", width: 12, dataSize: 3, description: "Support Beam (Yes/No)" },
      { key: "GUARD", header: "GUARD", dataType: "string", width: 12, dataSize: 3, description: "Riser Guard (Yes/No)" },
      { key: "PHYS_DMG", header: "PHYS_DMG", dataType: "string", width: 12, dataSize: 3, description: "Physical Damage (Yes/No)" },
      { key: "COAT_DMG", header: "COAT_DMG", dataType: "string", width: 12, dataSize: 3, description: "Coating Damage (Yes/No)" },
      { key: "CLAMP_QID", header: "CLAMP_QID", dataType: "string", width: 16, dataSize: 25, description: "Clamp QID" },
      { key: "ON", header: "ON", dataType: "string", width: 8, dataSize: 1, description: "ON" },
      { key: "NO_BOLTS", header: "NO_BOLTS", dataType: "number", width: 10, dataSize: 2, description: "No. of Bolts" },
      { key: "NO_NUTS", header: "NO_NUTS", dataType: "number", width: 10, dataSize: 2, description: "No. of Nuts" },
      { key: "NO_M_BOLTS", header: "NO_M_BOLTS", dataType: "number", width: 12, dataSize: 2, description: "No. of Missing Bolts" },
      { key: "NO_M_NUTS", header: "NO_M_NUTS", dataType: "number", width: 12, dataSize: 2, description: "No. of Missing Nuts" },
      { key: "NO_L_BOLTS", header: "NO_L_BOLTS", dataType: "number", width: 12, dataSize: 2, description: "No. of Loose Bolts" },
      { key: "NO_L_NUTS", header: "NO_L_NUTS", dataType: "number", width: 12, dataSize: 2, description: "No. of Loose Nuts" },
      { key: "NUT_SIZE", header: "NUT_SIZE", dataType: "number", width: 12, dataSize: 9, decSize: 3, description: "Nut Size" },
      { key: "BOLT_SIZE", header: "BOLT_SIZE", dataType: "number", width: 12, dataSize: 9, decSize: 3, description: "Bolt Size" },
      { key: "GAP", header: "GAP", dataType: "number", width: 10, dataSize: 9, decSize: 3, description: "Gap" },
      { key: "CP_IN", header: "CP_IN", dataType: "number", width: 10, dataSize: 5, description: "CP IN" },
      { key: "CP_OUT", header: "CP_OUT", dataType: "number", width: 10, dataSize: 5, description: "CP OUT" },
      { key: "GASKET_DMG", header: "GASKET_DMG", dataType: "string", width: 14, dataSize: 20, description: "Gasket Info" },
      { key: "REF_NAME", header: "REF_NAME", dataType: "string", width: 14, dataSize: 20, description: "Reference Name" },
      { key: "POSITION", header: "POSITION", dataType: "string", width: 14, dataSize: 20, description: "Position" },
      { key: "READ_THICK", header: "READ_THICK", dataType: "number", width: 12, dataSize: 9, decSize: 3, description: "Read Thickness" },
      ...SICS_COMMON_SUFFIX,
    ],
  },

  // 14. BSS - Bolted Support Inspection
  {
    id: "sics-bss",
    identifierCode: "BSS",
    sheetName: "BSS_BOLTED_SUPPORT",
    fileNameFormat: "yymmdd-nn-BSS.txt",
    queryStrategy: "INSP_RECORDS",
    inspectionTypeCode: ["BSS", "BOLT"],
    description: "Bolted Support Inspection Table Structure",
    columns: [
      ...SICS_COMMON_PREFIX,
      { key: "NO_BOLTS_PRES_MEMB", header: "NO_BOLTS_PRES_MEMB", dataType: "number", width: 14, dataSize: 3, description: "No. of Bolts Pres. Memb." },
      { key: "NO_BOLTS_LOSE_MEMB", header: "NO_BOLTS_LOSE_MEMB", dataType: "number", width: 14, dataSize: 3, description: "No. of Bolts Loose Memb." },
      { key: "NO_BOLTS_MIS_MEMB", header: "NO_BOLTS_MIS_MEMB", dataType: "number", width: 14, dataSize: 3, description: "No. of Bolts Missing Memb." },
      { key: "LINER_MEMB", header: "LINER_MEMB", dataType: "string", width: 12, dataSize: 3, description: "Liner Present Member End (Yes/No)" },
      { key: "LINER_COMP", header: "LINER_COMP", dataType: "string", width: 12, dataSize: 3, description: "Liner Present Comp. End (Yes/No)" },
      { key: "CLMP_COATING", header: "CLMP_COATING", dataType: "string", width: 14, dataSize: 3, description: "Clamp Coating Satisfactory (Yes/No)" },
      { key: "EARTHWIRE_BOLT", header: "EARTHWIRE_BOLT", dataType: "string", width: 14, dataSize: 3, description: "Earthing Wire/Bolt Present (Yes/No)" },
      { key: "BOLTS_NUTTED", header: "BOLTS_NUTTED", dataType: "string", width: 14, dataSize: 3, description: "All Bolts Double Nutted (Yes/No)" },
      { key: "WASHER_PRES", header: "WASHER_PRES", dataType: "string", width: 12, dataSize: 3, description: "Washers Present (Yes/No)" },
      { key: "GAP_TOP_MEMB", header: "GAP_TOP_MEMB", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "Max. Gap Top of Memb. (mm/in)" },
      { key: "GAP_BOT_MEMB", header: "GAP_BOT_MEMB", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "Max. Gap Bot. of Memb. (mm/in)" },
      { key: "GAP_TOP_COMP", header: "GAP_TOP_COMP", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "Max. Gap Top of Brace (mm/in)" },
      { key: "GAP_BOT_COMP", header: "GAP_BOT_COMP", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "Max. Gap Bot. of Brace (mm/in)" },
      { key: "FLNG_MEMB", header: "FLNG_MEMB", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "Max. Flange Misalign. Memb. (mm/in)" },
      { key: "FLNG_COMP", header: "FLNG_COMP", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "Max. Flange Misalign. Brace (mm/in)" },
      { key: "NO_BOLTS_PRES_COMP", header: "NO_BOLTS_PRES_COMP", dataType: "number", width: 14, dataSize: 3, description: "No. of Bolts Pres. Brace" },
      { key: "NO_BOLTS_LOSE_COMP", header: "NO_BOLTS_LOSE_COMP", dataType: "number", width: 14, dataSize: 3, description: "No. of Bolts Loose Brace" },
      { key: "NO_BOLTS_MIS_COMP", header: "NO_BOLTS_MIS_COMP", dataType: "number", width: 14, dataSize: 3, description: "No. of Bolts Missing Brace" },
      { key: "RISER_CP", header: "RISER_CP", dataType: "number", width: 12, dataSize: 5, description: "Riser CP (mV)" },
      { key: "RISER_CLMP_CP", header: "RISER_CLMP_CP", dataType: "number", width: 14, dataSize: 5, description: "Riser Clamp CP (mV)" },
      { key: "STUB_CP", header: "STUB_CP", dataType: "number", width: 12, dataSize: 5, description: "Stub CP (mV)" },
      { key: "MEMB_CLMP_CP", header: "MEMB_CLMP_CP", dataType: "number", width: 14, dataSize: 5, description: "Memb. Clamp CP (mV)" },
      { key: "MEMB_CP", header: "MEMB_CP", dataType: "number", width: 12, dataSize: 5, description: "Memb. CP (mV)" },
      { key: "RSR_CLMP_TYPE", header: "RSR_CLMP_TYPE", dataType: "string", width: 16, dataSize: 20, description: "Riser Clamp Type" },
      ...SICS_COMMON_SUFFIX,
    ],
  },

  // 15. CVS - Close Visual Inspection
  {
    id: "sics-cvs",
    identifierCode: "CVS",
    sheetName: "CVS_CLOSE_VISUAL",
    fileNameFormat: "yymmdd-nn-CVS.txt",
    queryStrategy: "INSP_RECORDS",
    inspectionTypeCode: ["CVI", "CLPIN", "CVS"],
    description: "Close Visual Inspection Table Structure",
    columns: [
      ...SICS_COMMON_PREFIX,
      { key: "LIGHT_METHOD", header: "LIGHT_METHOD", dataType: "string", width: 14, dataSize: 20, description: "Lighting Method" },
      { key: "LENGTH", header: "LENGTH", dataType: "number", width: 12, dataSize: 9, decSize: 3, description: "Length (m/ft)" },
      { key: "WIDTH", header: "WIDTH", dataType: "number", width: 12, dataSize: 9, decSize: 3, description: "Width (m/ft)" },
      ...SICS_COMMON_SUFFIX,
    ],
  },

  // 16. AFS - ACFM Survey
  {
    id: "sics-afs",
    identifierCode: "AFS",
    sheetName: "AFS_ACFM_SURVEY",
    fileNameFormat: "yymmdd-nn-AFS.txt",
    queryStrategy: "INSP_RECORDS",
    inspectionTypeCode: ["ACFM", "AFS"],
    description: "ACFM Survey Table Structure",
    columns: [
      ...SICS_COMMON_PREFIX,
      { key: "FILE_NAME", header: "FILE_NAME", dataType: "string", width: 16, dataSize: 20, description: "File Name" },
      { key: "PROB_NO", header: "PROB_NO", dataType: "string", width: 14, dataSize: 20, description: "Probe No." },
      { key: "ORIENTATION", header: "ORIENTATION", dataType: "string", width: 14, dataSize: 20, description: "Orientation Tested" },
      { key: "DIRECTION_TRAVL", header: "DIRECTION_TRAVL", dataType: "string", width: 16, dataSize: 20, description: "Direction of Travel" },
      { key: "CLCK_POS", header: "CLCK_POS", dataType: "string", width: 12, dataSize: 20, description: "Clock Position" },
      { key: "OPERATOR", header: "OPERATOR", dataType: "string", width: 16, dataSize: 20, description: "Operator Name" },
      { key: "PROBE_FL", header: "PROBE_FL", dataType: "string", width: 14, dataSize: 20, description: "Probe" },
      { key: "CWB", header: "CWB", dataType: "string", width: 16, dataSize: 20, description: "Chord / Weld / Brace" },
      { key: "PAGE", header: "PAGE", dataType: "number", width: 10, dataSize: 2, description: "Page" },
      { key: "REPORT", header: "REPORT", dataType: "string", width: 16, dataSize: 30, description: "Report" },
      { key: "C_WALL_THK3", header: "C_WALL_THK3", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "Chord 3 O'Clock" },
      { key: "C_WALL_THK6", header: "C_WALL_THK6", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "Chord 6 O'Clock" },
      { key: "C_WALL_THK9", header: "C_WALL_THK9", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "Chord 9 O'Clock" },
      { key: "C_WALL_THK12", header: "C_WALL_THK12", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "Chord 12 O'Clock" },
      { key: "B_WALL_THK3", header: "B_WALL_THK3", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "Brace 3 O'Clock" },
      { key: "B_WALL_THK6", header: "B_WALL_THK6", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "Brace 6 O'Clock" },
      { key: "B_WALL_THK9", header: "B_WALL_THK9", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "Brace 9 O'Clock" },
      { key: "B_WALL_THK12", header: "B_WALL_THK12", dataType: "number", width: 14, dataSize: 9, decSize: 3, description: "Brace 12 O'Clock" },
      ...SICS_COMMON_SUFFIX,
    ],
  },

  // 17. BTS - Bottom / Seabed Survey
  {
    id: "sics-bts",
    identifierCode: "BTS",
    sheetName: "BTS_SEABED_SURVEY",
    fileNameFormat: "yymmdd-nn-BTS.txt",
    queryStrategy: "PIPE_GEO_EVENTS",
    description: "Bottom / Seabed Survey Table Structure",
    columns: [
      ...SICS_COMMON_PREFIX,
      { key: "FACE", header: "FACE", dataType: "string", width: 12, dataSize: 20, description: "Face" },
      { key: "LEG1", header: "LEG1", dataType: "string", width: 12, dataSize: 20, description: "Leg 1" },
      { key: "DEPTH1", header: "DEPTH1", dataType: "number", width: 12, dataSize: 9, decSize: 3, description: "Depth 1 (m/ft)" },
      { key: "LEG2", header: "LEG2", dataType: "string", width: 12, dataSize: 20, description: "Leg 2" },
      { key: "DEPTH2", header: "DEPTH2", dataType: "number", width: 12, dataSize: 9, decSize: 3, description: "Depth 2 (m/ft)" },
      { key: "MID_POINT", header: "MID_POINT", dataType: "number", width: 12, dataSize: 9, decSize: 3, description: "Mid Point (m/ft)" },
      { key: "DEPTH3", header: "DEPTH3", dataType: "number", width: 12, dataSize: 9, decSize: 3, description: "Depth 3 (m/ft)" },
      { key: "DIST_LEG", header: "DIST_LEG", dataType: "number", width: 12, dataSize: 2, description: "Distance From Legs (m/ft)" },
      { key: "DIST_MIDPOINT", header: "DIST_MIDPOINT", dataType: "number", width: 14, dataSize: 2, description: "Distance From Midpoint (m/ft)" },
      ...SICS_COMMON_SUFFIX,
    ],
  },

  // 18. SZS - Splashzone Inspection
  {
    id: "sics-szs",
    identifierCode: "SZS",
    sheetName: "SZS_SPLASHZONE",
    fileNameFormat: "yymmdd-nn-SZS.txt",
    queryStrategy: "INSP_RECORDS",
    inspectionTypeCode: ["SPLASH", "SZS"],
    description: "Splashzone Inspection Table Structure",
    columns: [
      ...SICS_COMMON_PREFIX,
      { key: "CP_RDG", header: "CP_RDG", dataType: "number", width: 12, dataSize: 5, description: "CP Reading (mV)" },
      { key: "ASSESS", header: "ASSESS", dataType: "string", width: 16, dataSize: 20, description: "Assessment" },
      { key: "C01", header: "C01", dataType: "number", width: 10, dataSize: 9, decSize: 3, description: "UTWT 1 O'clock (mm/in)" },
      { key: "C02", header: "C02", dataType: "number", width: 10, dataSize: 9, decSize: 3, description: "UTWT 2 O'clock (mm/in)" },
      { key: "C03", header: "C03", dataType: "number", width: 10, dataSize: 9, decSize: 3, description: "UTWT 3 O'clock (mm/in)" },
      { key: "C04", header: "C04", dataType: "number", width: 10, dataSize: 9, decSize: 3, description: "UTWT 4 O'clock (mm/in)" },
      { key: "C05", header: "C05", dataType: "number", width: 10, dataSize: 9, decSize: 3, description: "UTWT 5 O'clock (mm/in)" },
      { key: "C06", header: "C06", dataType: "number", width: 10, dataSize: 9, decSize: 3, description: "UTWT 6 O'clock (mm/in)" },
      { key: "C07", header: "C07", dataType: "number", width: 10, dataSize: 9, decSize: 3, description: "UTWT 7 O'clock (mm/in)" },
      { key: "C08", header: "C08", dataType: "number", width: 10, dataSize: 9, decSize: 3, description: "UTWT 8 O'clock (mm/in)" },
      { key: "C09", header: "C09", dataType: "number", width: 10, dataSize: 9, decSize: 3, description: "UTWT 9 O'clock (mm/in)" },
      { key: "C10", header: "C10", dataType: "number", width: 10, dataSize: 9, decSize: 3, description: "UTWT 10 O'clock (mm/in)" },
      { key: "C11", header: "C11", dataType: "number", width: 10, dataSize: 9, decSize: 3, description: "UTWT 11 O'clock (mm/in)" },
      { key: "C12", header: "C12", dataType: "number", width: 10, dataSize: 9, decSize: 3, description: "UTWT 12 O'clock (mm/in)" },
      { key: "NOM_THK", header: "NOM_THK", dataType: "number", width: 12, dataSize: 9, decSize: 3, description: "Nominal Thick (mm/in)" },
      { key: "COAT_COVERAGE", header: "COAT_COVERAGE", dataType: "number", width: 14, dataSize: 3, description: "Coating Condition %" },
      ...SICS_COMMON_SUFFIX,
    ],
  },

  // 19. ITS - Item Inspection
  {
    id: "sics-its",
    identifierCode: "ITS",
    sheetName: "ITS_ITEMS",
    fileNameFormat: "yymmdd-nn-ITS.txt",
    queryStrategy: "INSP_RECORDS",
    inspectionTypeCode: ["ITEM", "ITS"],
    description: "Items Inspection Table Structure",
    columns: [
      ...SICS_COMMON_PREFIX,
      { key: "CP_RDG", header: "CP_RDG", dataType: "number", width: 12, dataSize: 7, decSize: 0, description: "CP Reading (mV)" },
      { key: "ITEM_TYPE", header: "ITEM_TYPE", dataType: "string", width: 16, dataSize: 20, description: "Type of Item" },
      { key: "INSPDESC", header: "INSPDESC", dataType: "string", width: 22, dataSize: 35, description: "Description" },
      ...SICS_COMMON_SUFFIX,
    ],
  },

  // 20. PGS - Platform General Inspection (ROV)
  {
    id: "sics-pgs",
    identifierCode: "PGS",
    sheetName: "PGS_ROV_GENERAL",
    fileNameFormat: "yymmdd-nn-PGS.txt",
    queryStrategy: "INSP_RECORDS",
    inspectionTypeCode: ["PGS", "ROVGEN"],
    description: "Platform General Inspection (ROV) Table Structure",
    columns: [
      ...SICS_COMMON_PREFIX,
      { key: "COUNTER_NO", header: "COUNTER_NO", dataType: "number", width: 12, dataSize: 6, decSize: 0, description: "Counter No." },
      { key: "I_DATE", header: "I_DATE", dataType: "date", width: 14, description: "Inspection Date" },
      { key: "I_TIME", header: "I_TIME", dataType: "string", width: 10, dataSize: 8, description: "Inspection Time" },
      { key: "DIVER", header: "DIVER", dataType: "string", width: 16, dataSize: 20, description: "Diver / Pilot Name" },
      { key: "ELV", header: "ELV", dataType: "number", width: 10, dataSize: 7, decSize: 2, description: "Elevation (m/ft)" },
      { key: "COMP_COND", header: "COMP_COND", dataType: "string", width: 16, dataSize: 20, description: "Component Condition" },
      { key: "COAT_COND", header: "COAT_COND", dataType: "string", width: 16, dataSize: 20, description: "Coating Condition" },
      { key: "DESCRIPTION", header: "DESCRIPTION", dataType: "string", width: 24, dataSize: 50, description: "Description" },
      { key: "MG_COND", header: "MG_COND", dataType: "string", width: 16, dataSize: 20, description: "Marine Growth Condition" },
      { key: "DEBRIS", header: "DEBRIS", dataType: "string", width: 14, dataSize: 20, description: "Debris" },
      { key: "CP_RDG", header: "CP_RDG", dataType: "number", width: 12, dataSize: 5, description: "CP Reading" },
      { key: "COMP_FACE", header: "COMP_FACE", dataType: "string", width: 12, dataSize: 6, description: "Component Face" },
      { key: "COMP_LEVEL", header: "COMP_LEVEL", dataType: "string", width: 14, dataSize: 20, description: "Component Level" },
      { key: "COMP_QID", header: "COMP_QID", dataType: "string", width: 16, dataSize: 16, description: "Component QID or LOGS" },
      { key: "FLOODED", header: "FLOODED", dataType: "string", width: 12, dataSize: 3, description: "Member Flooded? (Yes/No)" },
      { key: "PILE_EXPOSED", header: "PILE_EXPOSED", dataType: "string", width: 12, dataSize: 3, description: "Pile Exposed? (Yes/No)" },
      { key: "SCOUR_AT_LOC", header: "SCOUR_AT_LOC", dataType: "string", width: 14, dataSize: 10, description: "Scour At Location (Leg / Midpoint)" },
      { key: "SCOUR_AT_NODE", header: "SCOUR_AT_NODE", dataType: "string", width: 14, dataSize: 6, description: "Scour At Node No." },
      { key: "SCOUR_DEPTH", header: "SCOUR_DEPTH", dataType: "number", width: 12, dataSize: 9, decSize: 3, description: "Scour Depth" },
      { key: "SCOUR_DEPTH_U", header: "SCOUR_DEPTH_U", dataType: "string", width: 14, dataSize: 10, description: "Scour Depth Unit (mm/m/in/ft)" },
      { key: "SCOUR_BURIED", header: "SCOUR_BURIED", dataType: "number", width: 14, dataSize: 3, description: "Scour Buried Percentage" },
      { key: "HARD_GROWTH", header: "HARD_GROWTH", dataType: "number", width: 12, dataSize: 3, description: "Hard Growth %" },
      { key: "SOFT_GROWTH", header: "SOFT_GROWTH", dataType: "number", width: 12, dataSize: 3, description: "Soft Growth %" },
      { key: "HARD_THK12", header: "HARD_THK12", dataType: "number", width: 12, dataSize: 9, decSize: 3, description: "MGI Hard Thickness 12 O'Clock" },
      { key: "HARD_THK12_U", header: "HARD_THK12_U", dataType: "string", width: 12, dataSize: 10, description: "Thickness Unit (mm/in)" },
      { key: "HARD_THK3", header: "HARD_THK3", dataType: "number", width: 12, dataSize: 9, decSize: 3, description: "MGI Hard Thickness 3 O'Clock" },
      { key: "HARD_THK3_U", header: "HARD_THK3_U", dataType: "string", width: 12, dataSize: 10, description: "Thickness Unit (mm/in)" },
      { key: "HARD_THK6", header: "HARD_THK6", dataType: "number", width: 12, dataSize: 9, decSize: 3, description: "MGI Hard Thickness 6 O'Clock" },
      { key: "HARD_THK6_U", header: "HARD_THK6_U", dataType: "string", width: 12, dataSize: 10, description: "Thickness Unit (mm/in)" },
      { key: "HARD_THK9", header: "HARD_THK9", dataType: "number", width: 12, dataSize: 9, decSize: 3, description: "MGI Hard Thickness 9 O'Clock" },
      { key: "HARD_THK9_U", header: "HARD_THK9_U", dataType: "string", width: 12, dataSize: 10, description: "Thickness Unit (mm/in)" },
      { key: "AN_TYPE", header: "AN_TYPE", dataType: "string", width: 14, dataSize: 10, description: "Anode Type Name" },
      { key: "AN_DEPLETION", header: "AN_DEPLETION", dataType: "number", width: 14, dataSize: 3, description: "Anode Depletion % (25/50/75/76)" },
      { key: "INSP_TASK", header: "INSP_TASK", dataType: "string", width: 16, dataSize: 50, description: "Inspection Task (GVI, FMD, MGI)" },
      { key: "COMMENTS", header: "COMMENTS", dataType: "string", width: 30, dataSize: 250, description: "Comments" },
      ...SICS_COMMON_SUFFIX,
    ],
  },

  // 21. UCS - UT Calibration Inspection
  {
    id: "sics-ucs",
    identifierCode: "UCS",
    sheetName: "UCS_UT_CALIBRATION",
    fileNameFormat: "yymmdd-nn-UCS.txt",
    queryStrategy: "CALIBRATION",
    inspectionTypeCode: ["UTCLB", "UCS"],
    description: "UT Calibration Inspection Table Structure",
    columns: [
      ...SICS_COMMON_PREFIX,
      { key: "PROBE", header: "PROBE", dataType: "string", width: 14, dataSize: 20, description: "Probe" },
      { key: "PROBE_SIZE", header: "PROBE_SIZE", dataType: "string", width: 14, dataSize: 20, description: "Probe Size" },
      { key: "CLB_TYPE", header: "CLB_TYPE", dataType: "string", width: 14, dataSize: 20, description: "Calibration Type" },
      { key: "PROBE_FQ", header: "PROBE_FQ", dataType: "string", width: 14, dataSize: 20, description: "Probe Frequency" },
      { key: "RDG_1", header: "RDG_1", dataType: "number", width: 10, dataSize: 9, decSize: 3, description: "Reading 1" },
      { key: "RDG_2", header: "RDG_2", dataType: "number", width: 10, dataSize: 9, decSize: 3, description: "Reading 2" },
      { key: "RDG_3", header: "RDG_3", dataType: "number", width: 10, dataSize: 9, decSize: 3, description: "Reading 3" },
      { key: "RDG_4", header: "RDG_4", dataType: "number", width: 10, dataSize: 9, decSize: 3, description: "Reading 4" },
      { key: "RDG_5", header: "RDG_5", dataType: "number", width: 10, dataSize: 9, decSize: 3, description: "Reading 5" },
      { key: "RDG_6", header: "RDG_6", dataType: "number", width: 10, dataSize: 9, decSize: 3, description: "Reading 6" },
      { key: "LBL_1", header: "LBL_1", dataType: "string", width: 10, dataSize: 8, description: "Label 1" },
      { key: "LBL_2", header: "LBL_2", dataType: "string", width: 10, dataSize: 8, description: "Label 2" },
      { key: "LBL_3", header: "LBL_3", dataType: "string", width: 10, dataSize: 8, description: "Label 3" },
      { key: "LBL_4", header: "LBL_4", dataType: "string", width: 10, dataSize: 8, description: "Label 4" },
      { key: "LBL_5", header: "LBL_5", dataType: "string", width: 10, dataSize: 8, description: "Label 5" },
      { key: "LBL_6", header: "LBL_6", dataType: "string", width: 10, dataSize: 8, description: "Label 6" },
      { key: "INSPNO", header: "INSPNO", dataType: "string", width: 16, dataSize: 11, description: "Inspection No", required: true },
      { key: "JOBNAME", header: "JOBNAME", dataType: "string", width: 20, dataSize: 20, description: "SOW/Jobpack Name", required: true },
      { key: "STATUS", header: "STATUS", dataType: "string", width: 12, dataSize: 10, description: "SOW/Jobpack Status (OPEN / CLOSED)" },
      { key: "INSP_DONE", header: "INSP_DONE", dataType: "string", width: 10, dataSize: 3, description: "Inspection Done (Yes/No)" },
      { key: "REC_DATE", header: "REC_DATE", dataType: "date", width: 14, description: "Modified Date" },
      { key: "CMNTS", header: "CMNTS", dataType: "string", width: 40, dataSize: 4000, description: "Comments" },
    ],
  },

  // 22. ATS - Attachment Table Structure
  {
    id: "sics-ats",
    identifierCode: "ATS",
    sheetName: "ATS_ATTACHMENTS",
    fileNameFormat: "yymmdd-nn-ATS.txt",
    queryStrategy: "ATTACHMENTS",
    description: "All Attachments attached during inspection",
    columns: [
      { key: "ATTACH_ID", header: "ATTACH_ID", dataType: "number", width: 12, dataSize: 12, decSize: 0, description: "Attachment ID", required: true },
      { key: "STR_ID", header: "STR_ID", dataType: "number", width: 12, dataSize: 12, decSize: 0, description: "Structure ID", required: true },
      { key: "TITLE", header: "TITLE", dataType: "string", width: 20, dataSize: 20, description: "Structure Title" },
      { key: "PFIELD", header: "PFIELD", dataType: "string", width: 20, dataSize: 20, description: "Field Name" },
      { key: "PDESC", header: "PDESC", dataType: "string", width: 30, dataSize: 50, description: "Structure Desc" },
      { key: "DEF_UNIT", header: "DEF_UNIT", dataType: "string", width: 10, dataSize: 10, description: "Unit (Imperial/Metric)" },
      { key: "COMP_ID", header: "COMP_ID", dataType: "number", width: 12, dataSize: 12, decSize: 0, description: "Component ID" },
      { key: "ID_NO", header: "ID_NO", dataType: "string", width: 20, dataSize: 25, description: "Comp. ID No." },
      { key: "Q_ID", header: "Q_ID", dataType: "string", width: 16, dataSize: 16, description: "Comp. Q ID" },
      { key: "CODE", header: "CODE", dataType: "string", width: 8, dataSize: 2, description: "Comp. Type Code" },
      { key: "COMPDESC", header: "COMPDESC", dataType: "string", width: 24, dataSize: 40, description: "Comp. Desc" },
      { key: "S_NODE", header: "S_NODE", dataType: "string", width: 10, dataSize: 6, description: "Start Node" },
      { key: "F_NODE", header: "F_NODE", dataType: "string", width: 10, dataSize: 6, description: "End Node" },
      { key: "S_LEG", header: "S_LEG", dataType: "string", width: 8, dataSize: 2, description: "Start Leg" },
      { key: "F_LEG", header: "F_LEG", dataType: "string", width: 8, dataSize: 2, description: "End Leg" },
      { key: "ELV_1", header: "ELV_1", dataType: "number", width: 12, dataSize: 8, decSize: 3, description: "Start Elevation" },
      { key: "ELV_2", header: "ELV_2", dataType: "number", width: 12, dataSize: 8, decSize: 3, description: "End Elevation" },
      { key: "DIST", header: "DIST", dataType: "number", width: 10, dataSize: 6, decSize: 2, description: "Distance" },
      { key: "CLK_POS", header: "CLK_POS", dataType: "number", width: 10, dataSize: 4, decSize: 2, description: "Clock Position" },
      { key: "COMPTYPE", header: "COMPTYPE", dataType: "string", width: 20, dataSize: 30, description: "Component Type" },
      { key: "A_FILENAME", header: "A_FILENAME", dataType: "string", width: 24, dataSize: 60, description: "File Name", required: true },
      { key: "A_FILETYPE", header: "A_FILETYPE", dataType: "string", width: 10, dataSize: 3, description: "File Extension (JPG, PNG, PDF)" },
      { key: "A_PATH", header: "A_PATH", dataType: "string", width: 30, dataSize: 255, description: "File Storage Path" },
      { key: "ATT_TITLE", header: "ATT_TITLE", dataType: "string", width: 20, dataSize: 20, description: "Attachment Title" },
      { key: "DETAILS", header: "DETAILS", dataType: "string", width: 30, dataSize: 250, description: "Attachment Description" },
      { key: "INSPNO", header: "INSPNO", dataType: "string", width: 16, dataSize: 11, description: "Inspection No", required: true },
      { key: "INSP_ID", header: "INSP_ID", dataType: "number", width: 12, dataSize: 12, decSize: 0, description: "Inspection ID" },
      { key: "INSPCODE", header: "INSPCODE", dataType: "string", width: 10, dataSize: 6, description: "Inspection Code" },
      { key: "INSPNAME", header: "INSPNAME", dataType: "string", width: 24, dataSize: 50, description: "Inspection Name" },
      { key: "JOBNAME", header: "JOBNAME", dataType: "string", width: 20, dataSize: 20, description: "SOW/Jobpack Name", required: true },
      { key: "STATUS", header: "STATUS", dataType: "string", width: 12, dataSize: 10, description: "SOW/Jobpack Status" },
    ],
  },

  // 23. CMS - Component Master Table Structure
  {
    id: "sics-cms",
    identifierCode: "CMS",
    sheetName: "CMS_COMPONENT_MASTER",
    fileNameFormat: "yymmdd-nn-CMS.txt",
    queryStrategy: "COMPONENT_MASTER",
    description: "Component Master Table Structure",
    columns: [
      { key: "STR_ID", header: "STR_ID", dataType: "number", width: 12, dataSize: 12, decSize: 0, description: "Structure ID", required: true },
      { key: "TITLE", header: "TITLE", dataType: "string", width: 20, dataSize: 20, description: "Structure Title", required: true },
      { key: "PFIELD", header: "PFIELD", dataType: "string", width: 20, dataSize: 20, description: "Field Name" },
      { key: "PDESC", header: "PDESC", dataType: "string", width: 30, dataSize: 50, description: "Structure Desc" },
      { key: "DEF_UNIT", header: "DEF_UNIT", dataType: "string", width: 10, dataSize: 10, description: "Structure Unit Type" },
      { key: "COMP_ID", header: "COMP_ID", dataType: "number", width: 12, dataSize: 12, decSize: 0, description: "Component ID", required: true },
      { key: "ID_NO", header: "ID_NO", dataType: "string", width: 20, dataSize: 25, description: "Comp. ID No. (System Generated)" },
      { key: "Q_ID", header: "Q_ID", dataType: "string", width: 16, dataSize: 16, description: "Comp. Q ID (User Generated)", required: true },
      { key: "CODE", header: "CODE", dataType: "string", width: 8, dataSize: 2, description: "Comp. Type Code" },
      { key: "COMPDESC", header: "COMPDESC", dataType: "string", width: 24, dataSize: 40, description: "Comp. Desc" },
      { key: "S_NODE", header: "S_NODE", dataType: "string", width: 10, dataSize: 6, description: "Comp. Start Node" },
      { key: "F_NODE", header: "F_NODE", dataType: "string", width: 10, dataSize: 6, description: "Comp. End Node" },
      { key: "S_LEG", header: "S_LEG", dataType: "string", width: 8, dataSize: 2, description: "Comp. Start Leg" },
      { key: "F_LEG", header: "F_LEG", dataType: "string", width: 8, dataSize: 2, description: "Comp. End Leg" },
      { key: "ELV_1", header: "ELV_1", dataType: "number", width: 12, dataSize: 8, decSize: 3, description: "Comp. Start Elevation (m/ft)" },
      { key: "ELV_2", header: "ELV_2", dataType: "number", width: 12, dataSize: 8, decSize: 3, description: "Comp. End Elevation (m/ft)" },
      { key: "DIST", header: "DIST", dataType: "number", width: 10, dataSize: 6, decSize: 2, description: "Distance (m/ft)" },
      { key: "CLK_POS", header: "CLK_POS", dataType: "number", width: 10, dataSize: 4, decSize: 2, description: "Clock Position" },
      { key: "COMPTYPE", header: "COMPTYPE", dataType: "string", width: 20, dataSize: 30, description: "Component Type" },
      { key: "REC_DATE", header: "REC_DATE", dataType: "date", width: 14, description: "Last Modified Date" },
    ],
  },

  // 24. JMS - Jobpack / SOW Master Table Structure
  {
    id: "sics-jms",
    identifierCode: "JMS",
    sheetName: "JMS_JOBPACK_MASTER",
    fileNameFormat: "yymmdd-nn-JMS.txt",
    queryStrategy: "JOBPACK_SOW_MASTER",
    description: "Jobpack / SOW Master Table Structure",
    columns: [
      { key: "INSPNO", header: "INSPNO", dataType: "string", width: 16, dataSize: 11, description: "Inspection / SOW Report No.", required: true },
      { key: "JOBNAME", header: "JOBNAME", dataType: "string", width: 24, dataSize: 20, description: "SOW / Jobpack Name", required: true },
      { key: "ISTART", header: "ISTART", dataType: "date", width: 14, description: "SOW / Jobpack Start Date" },
      { key: "STATUS", header: "STATUS", dataType: "string", width: 14, dataSize: 10, description: "SOW / Jobpack Status (OPEN / CLOSED)", required: true },
    ],
  },
];

export const INITIAL_CLIENT_PROFILES: ClientProfile[] = [
  {
    id: "pcsb",
    code: "PCSB",
    name: "PCSB (PETRONAS Carigali)",
    fullName: "Petronas Carigali Sdn Bhd",
    country: "Malaysia",
    logoColor: "from-emerald-500 to-teal-700",
    description: "Petronas Carigali offshore structural integrity and pipeline data interface systems.",
    interfaces: [
      {
        id: "pcsb-sic",
        name: "SICS Interface",
        code: "SICS",
        systemTitle: "Structural Integrity Compliance System (Platforms)",
        targetStructureType: "PLATFORM",
        defaultFileFormat: "individual_xlsx",
        fileNamePattern: "PCSB_SICS_{STRUCTURE}_{YEAR}_{DATE}.zip",
        destinationFolder: "C:\\Offshore_Transfers\\PCSB\\SICS_Platform_Deliverables\\",
        description: "Official Petronas Carigali SICS 24-table individual files format (.xlsx, .txt tab-delimited, or .csv).",
        templates: PCSB_SICS_TEMPLATES,
      },
      {
        id: "pcsb-ipims",
        name: "iPIMS Interface",
        code: "iPIMS",
        systemTitle: "Pipeline Integrity Management System",
        targetStructureType: "PIPELINE",
        defaultFileFormat: "individual_xlsx",
        fileNamePattern: "PCSB_iPIMS_{PIPELINE}_{YEAR}_{DATE}.zip",
        destinationFolder: "C:\\Offshore_Transfers\\PCSB\\iPIMS_Pipeline_Deliverables\\",
        description: "Petronas Carigali Pipeline Integrity Management System (iPIMS) individual interface files for subsea pipelines.",
        templates: [
          {
            id: "ipims_header",
            identifierCode: "PLH",
            sheetName: "iPIMS_PIPE_HEADER",
            fileNameFormat: "yymmdd-nn-PLH.txt",
            queryStrategy: "STRUCTURE_SUMMARY",
            description: "Pipeline header, route information, diameter, burial status, and campaign",
            columns: [
              { key: "item_no", header: "NO", dataType: "number", width: 8, required: true },
              { key: "str_code", header: "PIPELINE_CODE", dataType: "string", width: 18, required: true },
              { key: "str_name", header: "PIPELINE_NAME", dataType: "string", width: 30, required: true },
              { key: "pfield", header: "FIELD_LOCATION", dataType: "string", width: 22 },
              { key: "start_kp", header: "KP_START", dataType: "number", width: 14 },
              { key: "end_kp", header: "KP_END", dataType: "number", width: 14 },
              { key: "total_length", header: "TOTAL_LENGTH_KM", dataType: "number", width: 18 },
              { key: "pipe_dia", header: "OUTER_DIA_INCH", dataType: "number", width: 16 },
              { key: "jobpack_no", header: "JOBPACK_REF", dataType: "string", width: 20 },
              { key: "survey_year", header: "SURVEY_YEAR", dataType: "string", width: 14 },
              { key: "export_date", header: "EXPORT_DATE", dataType: "date", width: 18 }
            ]
          },
          {
            id: "ipims_cp",
            identifierCode: "PCP",
            sheetName: "iPIMS_CP_SURVEY",
            fileNameFormat: "yymmdd-nn-PCP.txt",
            queryStrategy: "INSP_RECORDS",
            inspectionTypeCode: ["CPCLB", "CPINS", "PIPECP"],
            description: "Subsea pipeline continuous trailing-wire / stab cathodic protection potential profile",
            columns: [
              { key: "item_no", header: "NO", dataType: "number", width: 8, required: true },
              { key: "str_name", header: "PIPELINE_NAME", dataType: "string", width: 26, required: true },
              { key: "jobpack_no", header: "JOBPACK_NO", dataType: "string", width: 18 },
              { key: "kp_position", header: "KP_STATION", dataType: "number", width: 16, required: true },
              { key: "water_depth", header: "WATER_DEPTH_M", dataType: "number", width: 16 },
              { key: "cp_reading", header: "CP_READING_MV", dataType: "number", width: 18, required: true },
              { key: "easting", header: "EASTING_X", dataType: "number", width: 16 },
              { key: "northing", header: "NORTHING_Y", dataType: "number", width: 16 },
              { key: "protection_status", header: "CP_STATUS", dataType: "string", width: 18 },
              { key: "insp_date", header: "SURVEY_DATE", dataType: "date", width: 16 }
            ]
          },
          {
            id: "ipims_anode",
            identifierCode: "PAN",
            sheetName: "iPIMS_ANODE_SURVEY",
            fileNameFormat: "yymmdd-nn-PAN.txt",
            queryStrategy: "INSP_RECORDS",
            inspectionTypeCode: ["ANMIN", "ANODE"],
            description: "Pipeline bracelet / sacrificial anode depletion and physical condition",
            columns: [
              { key: "item_no", header: "NO", dataType: "number", width: 8, required: true },
              { key: "str_name", header: "PIPELINE_NAME", dataType: "string", width: 26, required: true },
              { key: "anode_ref", header: "ANODE_ID_TAG", dataType: "string", width: 20, required: true },
              { key: "kp_position", header: "KP_LOCATION", dataType: "number", width: 16, required: true },
              { key: "water_depth", header: "WATER_DEPTH_M", dataType: "number", width: 16 },
              { key: "anode_depletion", header: "DEPLETION_PCT", dataType: "string", width: 16 },
              { key: "cp_reading", header: "ANODE_CP_MV", dataType: "number", width: 18 },
              { key: "comp_cond", header: "PHYSICAL_CONDITION", dataType: "string", width: 22 },
              { key: "insp_date", header: "INSPECTION_DATE", dataType: "date", width: 16 }
            ]
          },
          {
            id: "ipims_freespan",
            identifierCode: "PFS",
            sheetName: "iPIMS_FREE_SPAN",
            fileNameFormat: "yymmdd-nn-PFS.txt",
            queryStrategy: "PIPE_GEO_EVENTS",
            queryFilter: { feature_type: "SPAN" },
            description: "Pipeline seabed unsupported span lengths, seabed clearance gaps, and coordinates",
            columns: [
              { key: "item_no", header: "NO", dataType: "number", width: 8, required: true },
              { key: "str_name", header: "PIPELINE_NAME", dataType: "string", width: 26, required: true },
              { key: "span_id", header: "SPAN_TAG", dataType: "string", width: 18, required: true },
              { key: "start_kp", header: "START_KP", dataType: "number", width: 14, required: true },
              { key: "end_kp", header: "END_KP", dataType: "number", width: 14, required: true },
              { key: "span_length", header: "SPAN_LENGTH_M", dataType: "number", width: 18, required: true },
              { key: "span_gap", header: "MAX_GAP_HEIGHT_M", dataType: "number", width: 18, required: true },
              { key: "water_depth", header: "WATER_DEPTH_M", dataType: "number", width: 16 },
              { key: "easting", header: "EASTING_X", dataType: "number", width: 16 },
              { key: "northing", header: "NORTHING_Y", dataType: "number", width: 16 },
              { key: "criticality", header: "SPAN_SEVERITY", dataType: "string", width: 18 },
              { key: "rectification", header: "REMEDIATION_PLAN", dataType: "string", width: 28 },
              { key: "survey_date", header: "SURVEY_DATE", dataType: "date", width: 16 }
            ]
          },
          {
            id: "ipims_seabed",
            identifierCode: "PSB",
            sheetName: "iPIMS_SEABED_PROFILE",
            fileNameFormat: "yymmdd-nn-PSB.txt",
            queryStrategy: "PIPE_GEO_EVENTS",
            description: "Pipeline burial, exposure, seabed crossing, mattress, and debris events",
            columns: [
              { key: "item_no", header: "NO", dataType: "number", width: 8, required: true },
              { key: "str_name", header: "PIPELINE_NAME", dataType: "string", width: 26, required: true },
              { key: "start_kp", header: "KP_START", dataType: "number", width: 14, required: true },
              { key: "end_kp", header: "KP_END", dataType: "number", width: 14 },
              { key: "event_name", header: "EVENT_TYPE", dataType: "string", width: 24, required: true },
              { key: "feature_type", header: "FEATURE_CATEGORY", dataType: "string", width: 20 },
              { key: "burial_depth", header: "BURIAL_DEPTH_M", dataType: "number", width: 18 },
              { key: "water_depth", header: "WATER_DEPTH_M", dataType: "number", width: 16 },
              { key: "debris_info", header: "DEBRIS_REMARKS", dataType: "string", width: 30 },
              { key: "easting", header: "EASTING_X", dataType: "number", width: 16 },
              { key: "northing", header: "NORTHING_Y", dataType: "number", width: 16 },
              { key: "survey_date", header: "SURVEY_DATE", dataType: "date", width: 16 }
            ]
          },
          {
            id: "ipims_anomalies",
            identifierCode: "PAD",
            sheetName: "iPIMS_ANOMALIES_DEFECTS",
            fileNameFormat: "yymmdd-nn-PAD.txt",
            queryStrategy: "ANOMALIES",
            description: "Pipeline defects, coating loss, mechanical dents, and integrity findings",
            columns: [
              { key: "item_no", header: "NO", dataType: "number", width: 8, required: true },
              { key: "anomaly_ref", header: "ANOMALY_REF_NO", dataType: "string", width: 20, required: true },
              { key: "str_name", header: "PIPELINE_NAME", dataType: "string", width: 26, required: true },
              { key: "kp_position", header: "KP_LOCATION", dataType: "number", width: 16 },
              { key: "defect_type", header: "DEFECT_TYPE", dataType: "string", width: 18, required: true },
              { key: "defect_category", header: "CATEGORY", dataType: "string", width: 18 },
              { key: "priority", header: "PRIORITY_RATING", dataType: "string", width: 18, required: true },
              { key: "status", header: "STATUS", dataType: "string", width: 14, required: true },
              { key: "description", header: "DEFECT_DESCRIPTION", dataType: "string", width: 45 },
              { key: "dimensions", header: "DIMENSIONS_LXW", dataType: "string", width: 20 },
              { key: "rectification", header: "ACTION_REQUIRED", dataType: "string", width: 40 },
              { key: "discovery_date", header: "DISCOVERY_DATE", dataType: "date", width: 16 }
            ]
          }
        ]
      }
    ]
  }
];

export const CLIENT_PROFILES = INITIAL_CLIENT_PROFILES;
